baseURL = "https://wolf-suite.web.app/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Wolf Suite"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Bots"
url = "#bots"
weight = 3
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 4

# Sitemap Menu
[[menu.sitemap]]
name = "About Wolf Suite"
url = "#about"
weight = 1
[[menu.sitemap]]
name = "Terms of Service"
url = "tos"
weight = 2
[[menu.sitemap]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 3
[[menu.sitemap]]
name = "Blog"
url = "blog"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
email = "wolfiediscord@gmail.com"
supportserver = "https://discord.gg/JMrvE3m"
